### ISSUE TITLE
Generating an observed-data object puts a non-serializable object in the 'objects' field

### ISSUE THREAD

**Issue by zrush-mitre** [oasis-open/cti-stix-generator#7]
Generate an `observed-data` object like so:

```
import stix2generator

gen = stix2generator.create_object_generator()

gen.generate('observed-data')
```

Here is an example object that was generated:

```{'created': '2021-10-24T10:30:33Z', 'spec_version': '2.1', 'labels': ['forget', 'town', 'budget', 'specific', 'air'], 'modified': '2022-05-10T21:25:36Z', 'lang': 'en', 'external_references': [{'description': 'Top few help election behind.', 'source_name': 'open'}, {'url': 'https://lee.com/', 'description': 'Break view figure language movie cut through.', 'source_name': 'radio', 'external_id': 'BkpAClDOmmJQkWL'}, {'url': 'https://smith.com/', 'source_name': 'top'}], 'objects': {'url--75c13cc5-6885-4bc0-960a-3f12c6d91b2f': URL(type='url', spec_version='2.1', id='url--75c13cc5-6885-4bc0-960a-3f12c6d91b2f', value='http://wright.biz/')}, 'last_observed': '2022-02-06T13:59:17Z', 'type': 'observed-data', 'id': 'observed-data--56917a71-696a-4404-87a7-a4bc50ca63c1', 'first_observed': '2021-10-17T00:33:11Z', 'number_observed': 667309173}```

The `objects` field is already deprecated, so we may want to get rid of it entirely, but the actual bug comes from the fact that the object is a `URL`, and not just a JSON object. If I try to add this object to a taxii server, for example, I get this error:

`TypeError: Object of type 'URL' is not serializable`

**Comment by chisholm** [comment]
Crud... yeah we changed STIXGenerator and ReferenceGraphGenerator to return parsed stix2 objects instead of dicts.  I forgot that it would have this side-effect.  The observable-container semantic uses ReferenceGraphGenerator to create the observable container, so it's getting the parsed objects now.  Blearg.  It's kind of ugly that we'd have to undo that work in this context. :(

The stix2 library's STIXJSONEncoder class would serialize that correctly I think, but TAXII client has no dependence on that library.  The dependency would have to be introduced, which is a separate decision.

I think including the deprecated "objects" field was a requirement that we were given.  I don't think it was up to us.
